### ISSUE TITLE
Entity mongo docs (src/database/documents/)

### ISSUE THREAD

**Issue by evabronskayaa** [IvanSvyatykh/SemestrDatabaseWork#2]
В целом в питоне нет жесткого правила: под каждый класс заводить отдельный модуль

Так что тут можно классы все в один модуль запихнуть.
Практическая значимость:
- меньше плодишь модули
- поскольку структуру отношений ты вряд ли будешь менять очень часто, то и заглядывать ты тоже туда будешь не каждый день)

**Comment by IvanSvyatykh** [comment]
Объединил классы в один модуль
